server:
  port: 8081
spring:
  h2:
    console:
      enabled: true
      path: /h2-fornecedor
  datasource:
    url: jdbc:h2:file:~/h2/fornecedor
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka