spring:
  h2:
    console:
      enabled: true
      path: /h2-transportador
  datasource:
    url: jdbc:h2:file:~/h2/transportador
    driverClassName: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: update
